### ISSUE TITLE
使用docker for windows开发, egg-bin dev没有检测到文件改动

### ISSUE THREAD

**Issue by ewinchen** [eggjs/egg#2662]
* **Node Version**: carbon
* **Egg Version**: 2.8.1
* **egg-bin**: 4.7.0
* **Plugin Name**: none
* **Plugin Version**: none
* **Platform**: windows 10 pro
* **Mini Showcase Repository**:

docker for windows下，用`volumes`绑定了宿主和容器的egg工程目录，在容器里运行`egg-bin dev`后，宿主修改文件，容器里的egg未能检测到。

Dockerfile
```
FROM node:carbon
```
docker-compose.yml
```
version: "3"

services:
  web:
    build: .
    container_name: egg
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src
    ports:
      - "7001:7001"
      - "5858:5858"
      - "9999:9999"
```
复现步骤

* egg-init

在宿主创建egg工程，并创建上述docker文件

* 启动容器
```
docker-compose up
```
* 进入容器
```
docker exec egg -it bash
```
* 启动egg

在容器的egg工程目录下`npm i && npm run dev`，egg正常启动。

* 修改文件

在宿主用vscode修改文件后egg不能检测到，但在容器内用`vim`查看可以看到文件已被修改。

该问题也会出现于`nodemon`，好像是文件系统监听事件的问题，`nodemon`可以使用`-L`命令解决，不知道egg是否有类似的命令或解决方案。

参考https://stackoverflow.com/questions/39239686/nodemon-doesnt-restart-in-windows-docker-environment
