### ISSUE TITLE
workers数量过多时会导致启动失败？

### ISSUE THREAD

**Issue by Anonymity94** [eggjs/egg#3088]
* **Node Version**: v8.11.4
* **Egg Version**: 2.12.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: CentOS Linux release 7.4.1708 (Core) 
* **Mini Showcase Repository**:

### 问题描述：
服务器的核数是24，不指定workers数量时启动时会出现错误；
当指定workers数量小一点时（例如4个），此时启动正常。

### 我的问题是：
导致这个问题的原因是什么？Issues中没有找到相关的答案。

### 相关日志截图：
![image](https://user-images.githubusercontent.com/13148447/46849065-1ddb8080-ce20-11e8-94aa-a93cfd3cdd1f.png)

**Comment by atian25** [comment]
你是 docker 的吧？是容器本身的限制。

另外，看到日志中 EGG_SERVER_ENV 为空，不是用 egg-scripts 启动的？（跟这个问题无关）

**Comment by popomore** [comment]
内存不够了吧

**Comment by Anonymity94** [comment]
@atian25 感谢回复。
1. 我提出的问题，是docker容器的限制，已查到相关原因。
2. 关于启动：

`docker-compose.yml` 中是直接使用的 `npm run start`
```
edge-report:
    image: thinkcraft:1.0
    container_name: edge-report
    restart: always
    user: thinkedge
    working_dir: /opt/edge-apps/edge-report
    command: npm run start
    environment:
      - TZ=Asia/Shanghai
    mem_limit: 512M
    memswap_limit: 512M
    volumes:
      - /opt/thinkedge/config:/opt/thinkedge/config
      - /opt/thinkedge/log:/opt/thinkedge/log
      - /opt/thinkedge/data:/opt/thinkedge/data
      - /opt/edge-apps/:/opt/edge-apps/
    ports:
      - "127.0.0.1:46059:46059"
    networks:
      - edge-net
    depends_on:
      - edge-distiller
```

`package.json`
```
"scripts": {
    "start": "egg-scripts start --workers=1 --title=egg-server-edge-report --ignore-stderr"
  },
```
