### ISSUE TITLE
可不可以写一篇关于docker部署eggjs的教程

### ISSUE THREAD

**Issue by Lancer-D** [eggjs/egg#3977]

**Comment by StephenSeraph** [comment]
我的实践：
启动参数为
```
"scripts": {
    "start": "egg-scripts start --workers=1 --title=egg-server-some-server"
}
```
`docker-compose.yml`大概是这样:
```
version: '3'
services:

  some-server:
    image: node:10.16.0
    ports:
      - "7001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm run tsc && npm start"
    # 或者
    # command: npm start
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    restart: always
```
主要就是不要后台启动就行了，其他没啥了，标准的Node服务。
