### ISSUE TITLE
docker-compose external_links egg-scripts 运行无效

### ISSUE THREAD

**Issue by Adgeros** [eggjs/egg#4671]
```
version: "3"
services:
  os:
    build: .
    container_name: os_server
    external_links:
      - mysql_server
      - redis_server
    ports:
      - 7001:7001
    networks:
      - app_net
networks:
  app_net:
    external: true

```

我用以上配置进行运行，链接不到 redis_server 容器，但是同样的配置我用 thinkjs 链接就可以连通，是在找不到是什么问题，有人遇到过这个问题吗
